Repository Aty-0/DMSH, pull requests merged in 2022-10, with the labels that each got.

#13 feature: console with commands
  Assets/Resources/Prefab/Characters/PlayerRoot.prefab
  Assets/Resources/Scripts/Misc/LogHandler.cs
  Packages/manifest.json
  Packages/packages-lock.json
Labels: enhancement, editor, UI

#15 UI: Improve responsiveness
  Assets/Resources/Prefab/Characters/Canvas.prefab
Labels: bug, UI

#17 Dev/kitakun
  Assets/Resources/Prefab/Characters/PlayerRoot.prefab
  Assets/Resources/Prefab/Misc/BonusScoreBuff.prefab
  Assets/Resources/Prefab/Misc/BonusWeaponBuff.prefab
  Assets/Resources/Prefab/UI/Canvas.prefab
  Assets/Resources/Prefab/UI/Canvas.prefab.meta
  Assets/Resources/Prefab/UI/StaticBackgroundCanvas.prefab
  Assets/Resources/Prefab/UI/StaticBackgroundCanvas.prefab.meta
  Assets/Resources/Scenes/DMSH_SampleScene.unity
  Assets/Resources/Scripts/Characters/PlayerController.cs
  Assets/Resources/Scripts/UI/UIBuildVersionText.cs
  Assets/Resources/Scripts/UI/UI_Root.cs
  Assets/Resources/Scripts/UI/UI_Root.cs.meta
  Assets/Resources/Scripts/Utils.meta
  Assets/Resources/Scripts/Utils/Instance.cs
  Assets/Resources/Scripts/Utils/Instance.cs.meta
Labels: UI

#20 Micro improve
  Assets/Resources/Scripts/LevelSpecifics/EnemyActiveField.cs
  Assets/Resources/Scripts/Misc/Screen/ResizableGameElements.cs
Labels: gameplay

#27 Dev/kitakun
  Assets/DMSH/Data/ProjectilePatterns/Fly/Default_PlayerFlyPattern.asset
  Assets/DMSH/Data/ProjectilePatterns/Fly/RandomMovement.asset
  Assets/DMSH/Data/ProjectilePatterns/Spawn/Spawn_DefaultPlayer.asset
  Assets/DMSH/Scripts/Characters/PlayerController.cs
  Assets/DMSH/Scripts/Objects/Projectiles/Bullet.cs
  Assets/DMSH/Scripts/Objects/Projectiles/Editor/ProjectileBehaviorStepEditor.cs
  Assets/DMSH/Scripts/Objects/Projectiles/Editor/ProjectileModificatorEditor.cs
  Assets/DMSH/Scripts/Objects/Projectiles/Editor/ProjectileModificatorEditor.cs.meta
  Assets/DMSH/Scripts/Objects/Projectiles/Editor/ProjectileSpawnStepStructEditor.cs
  Assets/DMSH/Scripts/Objects/Projectiles/ProjectileFlyBehaviorScriptableObject.cs
  Assets/DMSH/Scripts/Objects/Projectiles/ProjectileModificator.cs
  Assets/DMSH/Scripts/Objects/Projectiles/ProjectileModificator.cs.meta
  Assets/DMSH/Scripts/Objects/Projectiles/ProjectileModificatorStateStruct.cs
  Assets/DMSH/Scripts/Objects/Projectiles/ProjectileModificatorStateStruct.cs.meta
  Assets/DMSH/Scripts/Objects/Projectiles/ProjectileStateStruct.cs
  Assets/DMSH/Scripts/Utils/MathUtils.cs
  Assets/DMSH/Scripts/Utils/Pools/GenericReusableList.cs
  Assets/DMSH/Scripts/Utils/Pools/GenericReusableList.cs.meta
  Assets/DMSH/Scripts/Utils/World2DUtils.cs
Labels: gameplay
